apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-custom-test
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
